# --------- Etapa de build ---------
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /app

# Copiar archivo de proyecto y restaurar dependencias
COPY NetAPI.csproj ./
RUN dotnet restore

# Copiar todo el código
COPY . ./

# Publicar aplicación en modo Release
RUN dotnet publish -c Release -o out

# --------- Etapa runtime ---------
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

# Copiar archivos publicados
COPY --from=build /app/out .

# Configurar puerto
ENV ASPNETCORE_URLS=http://+:8083
EXPOSE 8083

ENTRYPOINT ["dotnet", "NetAPI.dll"]